/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RacketCustomizerRouteImport } from './routes/racket-customizer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminPaymentsRouteImport } from './routes/admin-payments'
import { Route as AdminOrdersRouteImport } from './routes/admin-orders'
import { Route as AdminCustomersRouteImport } from './routes/admin-customers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RacketCustomizerRoute = RacketCustomizerRouteImport.update({
  id: '/racket-customizer',
  path: '/racket-customizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin-payments',
  path: '/admin-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin-orders',
  path: '/admin-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin-customers',
  path: '/admin-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-customers': typeof AdminCustomersRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/racket-customizer': typeof RacketCustomizerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-customers': typeof AdminCustomersRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/racket-customizer': typeof RacketCustomizerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-customers': typeof AdminCustomersRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/racket-customizer': typeof RacketCustomizerRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-customers'
    | '/admin-orders'
    | '/admin-payments'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/payment-failed'
    | '/payment-success'
    | '/privacy'
    | '/racket-customizer'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-customers'
    | '/admin-orders'
    | '/admin-payments'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/payment-failed'
    | '/payment-success'
    | '/privacy'
    | '/racket-customizer'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-customers'
    | '/admin-orders'
    | '/admin-payments'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/payment-failed'
    | '/payment-success'
    | '/privacy'
    | '/racket-customizer'
    | '/reset-password'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  RacketCustomizerRoute: typeof RacketCustomizerRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racket-customizer': {
      id: '/racket-customizer'
      path: '/racket-customizer'
      fullPath: '/racket-customizer'
      preLoaderRoute: typeof RacketCustomizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-payments': {
      id: '/admin-payments'
      path: '/admin-payments'
      fullPath: '/admin-payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-orders': {
      id: '/admin-orders'
      path: '/admin-orders'
      fullPath: '/admin-orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-customers': {
      id: '/admin-customers'
      path: '/admin-customers'
      fullPath: '/admin-customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  RacketCustomizerRoute: RacketCustomizerRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
